# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ServerStatus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, message: str=None):  # noqa: E501
        """ServerStatus - a model defined in Swagger

        :param message: The message of this ServerStatus.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'message': str
        }

        self.attribute_map = {
            'message': 'message'
        }
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ServerStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServerStatus of this ServerStatus.  # noqa: E501
        :rtype: ServerStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this ServerStatus.

        A few words describing the current status of the server  # noqa: E501

        :return: The message of this ServerStatus.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ServerStatus.

        A few words describing the current status of the server  # noqa: E501

        :param message: The message of this ServerStatus.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message
